### ISSUE TITLE
[Suggestion] Auto Target changes

### ISSUE THREAD

**Issue by Doxmia** [UnknownX7/ReAction#11]
Is it possible that if you have a friendly targeted that auto target will auto target the nearest enemy for a "harmful" ability/spell? 

Alternatively, another feature could be disabling clicking friendly bodies while in combat (which is what tends to cause this issue in the first place).

**Comment by ShinjukuCurry** [comment]
Second this as well, accidentally clicking on party members has always been somewhat of a mild annoyance for myself.

Ideally a click filter that ignores only allies (While still retaining the functionality of clicking on enemies and interactable objects, and using mouseover actions) would solve this issue. This was actually requested on SimpleTweaks before but it never received much attention.

Bonus if it allows for the "fuzzy selection" ability seen in-game by default holding X - Where even if your mouse doesn't actually click on a target, the closest one from your cursor will be selected.

**Comment by UnknownX7** [comment]
I think it would be better for SimpleTweaks to implement click filtering as it already has a similar feature, as well as to avoid any potential conflicts. However, the first suggestion will be available in the next update.
