### ISSUE TITLE
Dawntrail MCH Drill doesn't queue with enable queue adjustments

### ISSUE THREAD

**Issue by natis1** [UnknownX7/ReAction#118]
(pre level 100, maybe also applies at level 100 not sure)
Drill does not add itself to the queue early if you bump up the queue threshold. In fact it seems to only add itself to the queue at the normal time. it also does not add itself to the queue if its on cooldown but won't be on cooldown when the gcd rolls around. Other mch abilities seem to work fine.

**Comment by Yurei17** [comment]
I would like to add to this issue that living muse, a pictomancer's ogcd, does not queue properly when you have queue adjustment enabled.

**Comment by Beetle-Lord** [comment]
It seems there are multiple abilities falling under this bug. Tetragrammaton has trouble queueing as well if "Enable Queue Adjustments" is enabled.

**Comment by aradiel** [comment]
I tested at level 96 and it didn't have the issue. My theory is that it maybe has something to do with the multiple uses it acquires

**Comment by UnknownX7** [comment]
This should be fixed in the latest version.
