### ISSUE TITLE
Salted Earth Auto Target Issue

### ISSUE THREAD

**Issue by F-a-y-t-h** [UnknownX7/ReAction#12]
65ce890d8a6b67e4469ddac52fadd7fd5e7cdf83 Causes the dark knight skill salted earth to trigger a auto target unnecessarily 

(personally i also would only want the tab auto target to trigger if i have 'no' active target, so if that could be made it own toggle that would be great)

**Comment by UnknownX7** [comment]
I cannot reproduce the salted earth bug, the action fails one of my checks so I'm not sure how it could be happening. However, I've split auto target into two options.

**Comment by F-a-y-t-h** [comment]
A video of the issue; doesn't trigger a auto target if your self is selected but i'm not sure what more i could add,
https://puu.sh/IyLkC/a445bfaacd.webm

**Comment by UnknownX7** [comment]
Let me know if this is still occurring after the latest update. I've added some debug logging that should hopefully provide some clues if it is. You can access it through `/xllog` and changing this setting.
![ffxiv_dx11_2021-12-27_08-06-15](https://user-images.githubusercontent.com/12263784/147512777-bf041d17-16ae-40bd-96f6-77e9c257d252.png)

**Comment by Chiruadr** [comment]
Autos start when using MNK Formless Fist. Issue from spells enabling autos. Maybe related

**Comment by F-a-y-t-h** [comment]
--------------------------------
09:47:08.811 | DBG [ReAction] UseAction called 1, 3639 -> 3639, 40000A51, 0, 0, 0
--------------------------------
09:47:08.811 | DBG [ReAction] Checking stacks
--------------------------------
09:47:08.811 | DBG [ReAction] Attempting to swap target 3639, 40000A51
--------------------------------
09:47:08.811 | DBG [ReAction] Target swapped 40000A51 -> 40000A52
--------------------------------
09:47:09.244 | DBG [ReAction] UseAction called 1, 3639 -> 3639, 40000A52, 0, 0, 0
--------------------------------
09:47:09.244 | DBG [ReAction] Checking stacks
--------------------------------
09:47:09.244 | DBG [ReAction] Attempting to swap target 3639, 40000A52
--------------------------------
09:47:09.244 | DBG [ReAction] Target swapped 40000A52 -> 40000A51
--------------------------------

**Comment by UnknownX7** [comment]
Can you test this one more time, I added a little bit more info to the "Attempting to swap target" debug logs. It should tell me if the issue is Lumina or not.

**Comment by F-a-y-t-h** [comment]
`08:23:19.152 | DBG [ReAction] Attempting to swap target 3639, 400003DE, Action#3639, True`

**Comment by UnknownX7** [comment]
Do you use any sort of game file modification? Lumina isn't pulling the correct information it seems. If you want to double check, you can install Godbert from https://github.com/xivapi/SaintCoinach/releases and then look up the Action sheet for Salted Earth and the correct version should have these values:

![image](https://user-images.githubusercontent.com/12263784/147737160-a8ff1e78-ca74-4edb-964e-87d35b29de31.png)

According to your game, "CanTargetHostile" is true which is where this problem is stemming from.

**Comment by F-a-y-t-h** [comment]
Godbert has it correctly, and it was still doing it when it was the only plugin loaded... my Dark Knight is lv80 https://puu.sh/IzoSf/faf196aec3.png

**Comment by F-a-y-t-h** [comment]
Issue no longer pops up so closing this.
