### ISSUE TITLE
Enable Instant Ground Targets prevents aiming actions manually.

### ISSUE THREAD

**Issue by Zeemgeem** [UnknownX7/ReAction#127]
When this setting is turned on all ground target actions seem to almost always be placed on your target rather than your mouse, despite what the setting claims. I do not have any stacks, so it can't be getting overwritten.

**Comment by Zeemgeem** [comment]
I was misinformed. It's actually "Enable Ground Target Queueing", which has a bug report already. Apologies!

**Comment by Cloud7050** [comment]
For reference, it is #103
