### ISSUE TITLE
[Bug] Unable to detonate Earthly Star (no stellar detonation change on ability)

### ISSUE THREAD

**Issue by crystal-prison** [UnknownX7/ReAction#138]
Please see : https://github.com/UnknownX7/ReAction/issues/137#issuecomment-2495156338

I believe this is related to the previous Sundering options no longer being available in the plugin.
Do note I have to execute the ID to be placed on my hot bar to use it at all. "/ac" override options for macros does not work either.

Thanks.

**Comment by UnknownX7** [comment]
Wasn't able to reproduce, can you update to the latest version and check if the sundering option was enabled?
