### ISSUE TITLE
Documentation  request

### ISSUE THREAD

**Issue by gerrykoh** [UnknownX7/ReAction#14]
First of all thank you so much for making this! I appreciated your easy to follow installation instructions. Would it be possible to get some documentation on the various target types? Things like SoftTarget vs UITarget vs FocusTarget etc.

thanks again!

**Comment by pincoide** [comment]
Those targets are pretty simple:
- Soft target: the soft target is the "pre-target" you get using the gamepad or 4 in the numpad where you get that aim mark on a mob.
- UI Target: this is the mouse over target when you are pointing an healthbar.
- Field Target: this is the mouse over target when you are pointing a mob (not the healthbar the actual mob).
- Focus target: this is the normal focus target that already exist in the game and you set with F (not sure if that's the default hotkey).

**Comment by gerrykoh** [comment]
Thank you! Now that I understand the targets it is working well!
