### ISSUE TITLE
Suggestion/bug: Setting mutiple abilities per action fails.

### ISSUE THREAD

**Issue by Dajova** [UnknownX7/ReAction#16]
So this is a pretty annoying bug/oversight when trying to combine some abilities using priorities...
So im trying to set Sidewinder to use Empyreal Arrow > Bloodlettter when it's on cooldown, but it seems it's unable to distinguish what is on cooldown when on the same target.
It was fine when i combined Shadowbite with Rain of Death, but that's because Shadowbite is a weaponskill and not an ability. In fact, it still uses ogcds as a gcd...
The only workaround i've been able to find so far is to set them on field/ui target, but that just feel clunky...
I had the same problem when i was trying to combine Interject with Shield Lob (eg. use Interject when in melee range, Shield Lob when not in melee range) and had to work around with using fieldtarget there as well.
Would it be possible to fix this? It's one of the few "features" that i actually miss.

**Comment by coco35700** [comment]
Same here, i'm new to this plugin and it's something i could do on MOAction. Dunno if i'm not doing the right thing or if ReAction doesnt allow it but i can't find a way to bind multiple skills to a specific one based on availability. It's basically what is done on such macro :

/micon "Fleche"
/merror off
/ac "Fleche" <t>
/ac "Contre Sixte" <t>

Other than that, absolutely great plugin ! (maybe what i'm asking is already there and i'm just dumb)
