### ISSUE TITLE
Enhanced Auto Face Target?

### ISSUE THREAD

**Issue by ShinjukuCurry** [UnknownX7/ReAction#2]
Can you explain which skills are affected by this setting? The description says "Actions that don't require facing a target will no longer auto face the target", but I am confused as to how this applies to effect a noticeable gameplay change.

**Comment by UnknownX7** [comment]
Most things that target allies don't actually require looking at the ally, such as healing. Its not as noticeable for legacy controls, but standard users are forced into walking towards the ally unless they wiggle their camera.
