### ISSUE TITLE
[Suggestion] Option to ignore backwards dashes for "Camera Relative Dashes"

### ISSUE THREAD

**Issue by Alukah** [UnknownX7/ReAction#23]
Any chance you could add a way to separate elusive jump from the rest of the dashes for "camera relative dashes"? Unlike en avant or hell ingress, if you want to move forward with elusive jump it actually works better if you to turn your character around while camera is facing where you want to go. The way it works with the plugin I have to turn around and blindly jump backwards.

**Comment by Megasder** [comment]
So make elusive jump go the opposite way of the camera/go forward?

**Comment by Alukah** [comment]
I honestly was thinking of just leaving elusive jump unaffected by the plugin altogether, so you can still "backflip forward" as you do with the plugin disabled.
