### ISSUE TITLE
GCD queuing does not appear to function

### ISSUE THREAD

**Issue by Mike2k9** [UnknownX7/ReAction#25]
A prime QOL that MOAction functionality had was that spells, when stacked, behave like they would normally, adhering to global cooldown queuing (0.5 seconds button press before GCD is done queues the next action).

It does not appear that currently  ReAction allows for this to function, basically meaning that it follows the same janky FFXIV macro system of not allowing actions to be queued when macro'd and is the prime cause of rendering the built-in macro system of FFXIV useless for combat.

Example: stacking Gemshine and Ruin together for SMN worked perfectly and allowed action queuing using the (now outdated) MOAction plugin. This functionality does not appear to work for ReAction and would mean the world of difference if it did.

**Comment by fjgreer** [comment]
Are you sure? I use the latest version of ReAction and queuing works fine, especially for SMN.  I switched from MOAction to this because a stack of Gemshine and Ruin had a 50/50 chance of being either Gemshine OR Ruin.

**Comment by Mike2k9** [comment]
Yep, just confirmed it again, have an action stack made of Ruin and Gemshine.
top-right field:
Gemshine 

bottom-right field
Target Gemshine
Target Ruin

Gemshine queueing works just fine, but as soon as any summon phase is over and Gemshine is greyed out, Ruin will cast, but only when the GCD is completely done. I can't queue Ruin starting 0.5 seconds before the GCD comes up.

**Comment by fjgreer** [comment]
Huh, you're right.  I never noticed because I'm a button spammer anyway.  It also doesn't work if you have it set up like this: 
![image](https://user-images.githubusercontent.com/1480421/147844623-b804e579-d017-44b9-b5c2-2866216e2912.png)
