### ISSUE TITLE
"Enable Queuing More" seems to prevent usage of all items now.

### ISSUE THREAD

**Issue by AkiraChisaka** [UnknownX7/ReAction#26]
It seems like [this commit](https://github.com/UnknownX7/ReAction/commit/4108adb8f46ab67551bcee6b0d2945e12de788ae) have broke something.

After updating, when "Enable Queuing More" option is toggled on, using items will now play the animation, the item will go on CD, but no item is consumed and no effect is applied.

For example, 85 Dex Pots here:

![image](https://user-images.githubusercontent.com/47231500/147799489-afbbf0d0-ef76-4b01-b2b6-4823ee960319.png)

After using one, the animation will play, the "skill" will go on CD,

![image](https://user-images.githubusercontent.com/47231500/147799495-1707c0e1-0e06-4729-9819-939c6dd07c51.png)

But the amount of Dex Pots is still 85, and no buff is received.

The same thing happens for Food, so I assume all items are like this.

Meanwhile, sprint functions perfectly now! So I think the commit fixed what it needs to fix lol.

**Comment by UnknownX7** [comment]
Bug with MoAction

**Comment by AkiraChisaka** [comment]
Oh yeah, forgot to close this, thanks X!
