### ISSUE TITLE
Instant Ground Targets - displaying reticle in combat

### ISSUE THREAD

**Issue by VivyBehe** [UnknownX7/ReAction#27]
Didn't have any issues with this option beforehand in instances, would set ground targets down instantly wherever.

However, now whenever I use Earthly Star in a duty it will display the reticle and won't place instantly - I have to spam my keybind to set it down. Out of duty, in the housing area for example, this option works flawlessly without the reticle displaying and instantly sets the Earthly Star down.

**Comment by UnknownX7** [comment]
When did it break? I'm not able to reproduce this unfortunately.
