### ISSUE TITLE
Game FPS drops to 2FPS on ability search

### ISSUE THREAD

**Issue by vickyorlo** [UnknownX7/ReAction#29]
As the title says, whenever I try to add an ability to a stack, opening the ability search window and then starting to type a name drops the game's framerate down to single digits. The framerate returns once the window is closed. This makes it essentially impossible to use the plugin because the low framerate makes the textbox incredibly unresponsive. There is no heightened CPU, RAM or GPU usage while this happens, everything stays normal.
Note, however, that I'm running the game on Linux through Wine. I haven't seen a problem like this with other plugins, though.

**Comment by UnknownX7** [comment]
The search is cached now so this should be fixed.
