### ISSUE TITLE
[QoL] Sort/Reorder Stack Entries

### ISSUE THREAD

**Issue by Araiia** [UnknownX7/ReAction#31]
It is visually confusing to search for/organize the spells in a given stack - would love an option to have them sorted by job, alphabetically, or in a manual order. Currently, new entries are added from the bottom which means that if I later add another action from a job, it is going to be separated from the other actions I'd already added from that job - alternatively I can make a lot of different stacks for each job, but result in a lot of clutter in the stack list..

![ffxiv_dx11_2022-01-03_18-34-14](https://user-images.githubusercontent.com/41348845/147991617-f07b6d85-6ab7-42c2-96a3-9ceaa770da0c.png)

**Comment by UnknownX7** [comment]
9b9183a4f23356cf53fdad3c90472b6dd8f0a45e
