### ISSUE TITLE
Can't recreate Dragon Sight macro

### ISSUE THREAD

**Issue by amerenth** [UnknownX7/ReAction#32]
I cannot seem to recreate the traditional Dragon Sight macro with ReAction. I have previously with moaction as shown on the left here. The stack should work like the macro does in game, but queueable. So, check to see if its usable on party members 2/3/etc., then failing that because of range, use it anyways to give just myself the buff. Instead though, it seems to stop at the top of the stack. It'll work on 2, but if 2 is out of range, it fails completely and I can't press the button to buff 3 or myself instead. I've tried a bunch of different things but nothing works. Apologies if I'm an idiot and missing something obvious

![drg stuff](https://user-images.githubusercontent.com/97151040/148174089-82141d02-dd21-4d3e-8d17-4aac1d0007eb.jpg)

_(I consider this part resolved as per below comment) Also, a different issue I've noticed for Dragoons, when using Auto Target for our aoe attacks (that have to target the first mob), only Draconian Fury and Nastrond automatically tab. None of our other line attacks tab. Our jumps don't auto target either but I don't know if those are supposed to nor have I tested that much since I prefer hover jumping._ 

Thanks for the help either way. I love the work you've put in here.

**Comment by amerenth** [comment]
I discovered the reason Nastrond and Draconian Fury were the only ones auto tabbing was because they were the only ones not used as stacks for my hover abilities. I tested it for the other abilities and as soon as I removed them from my stacks they were able to auto target. I don't know if that's intended though

**Comment by ShinjukuCurry** [comment]
Dragon Sight works for me no problem. You need to check the "Fail if out of range" box.

**Comment by amerenth** [comment]
Thanks, That was one of my first tests but I must have had personal range issues going on at the time. Everything works now either way though
