### ISSUE TITLE
Phantom Kamaitachi and Bunshin combo

### ISSUE THREAD

**Issue by drip723** [UnknownX7/ReAction#47]
At the moment, much like meditation and Forbidden chakra without the split, as ninja, mashing your Bunshin key might queue a Phantom Kamaitachi that you did not want to use.
Placing either of those through both stack option and place on hotbar option just creates a new button that does the same as the in game default button does.
Is it possible to add a toggle to break this combo?

Bunshin ID 16493
Phantom kamaitachi ID 25774

**Comment by UnknownX7** [comment]
aa6f7b3dd070c2fcb068852118b7b9a54c505f83
