### ISSUE TITLE
High Jump/Jump and Mirage Dive

### ISSUE THREAD

**Issue by 720mmHowizter** [UnknownX7/ReAction#48]
Suggestion identical to [https://github.com/UnknownX7/ReAction/issues/47](https://github.com/UnknownX7/ReAction/issues/47) But for DRG's High Jump/Jump and Mirage Dive.
New patch now makes High Jump/Jump change to Mirage Dive while under the effect of Mirage Dive Ready.
An option to separate the actions like how it was before the patch would be amazing.

Jump action# 9
High Jump action# 16478
Mirage Dive action# 7399

**Comment by UnknownX7** [comment]
aa6f7b3dd070c2fcb068852118b7b9a54c505f83
