### ISSUE TITLE
Mouseover targeting not working

### ISSUE THREAD

**Issue by Iaotle** [UnknownX7/ReAction#50]
Field/UI mouseover isn't working correctly after 6.1.

**Comment by UnknownX7** [comment]
Not currently able to reproduce this, can you open "/xllog" and then set it to debug level and then send me a picture/log of it occurring? Also, an export of the stack thats failing.

![image](https://user-images.githubusercontent.com/12263784/163568817-0ae1df75-f886-4441-a590-6dc2539f7796.png)

**Comment by Iaotle** [comment]
Hmm, was probably just me being an idiot. Not sure why it wasn't working before.
