### ISSUE TITLE
[Bug] Target of Target doesn't work in 6.2

### ISSUE THREAD

**Issue by Chiruadr** [UnknownX7/ReAction#64]
TargetsTarget option in stacks doesn't seem to work at all after updated

**Comment by jundong321** [comment]
+1

**Comment by rz-1** [comment]
target of target for me:
* dps skills ARE working (targeting an ally and using a dps skill on their target ie: Dosis)
* healing/mitigation skills are NOT working (targeting an enemy and using a heal/mit skill ie: Taurochole)

**Comment by UnknownX7** [comment]
Should be fixed, lmk.

**Comment by Chiruadr** [comment]
Seems to work fine now. Thank you very much.
