### ISSUE TITLE
[Suggestion] add decombo for Minor Arcana

### ISSUE THREAD

**Issue by KataLystTB** [UnknownX7/ReAction#65]
Minor Arcana and lord/lady of crowns now share a button which is great for reducing button bloat however presents the problem of now no longer showing the cooldown of minor arcana, as well as preventing double weaving due to the 1s innate cooldown between the action use that was not present when the abilities were seperate.
I am wondering if its possible to have the minor arcana spell by itself visible on a hotbar somewhere (like how it is in the character >abilities page where the cooldown is visible) so that the cooldown can be tracked properly.

**Comment by wacomintuos** [comment]
Please add this.
