### ISSUE TITLE
[Suggestion] Enable the queueing of macro actions.

### ISSUE THREAD

**Issue by geppeisenpai** [UnknownX7/ReAction#71]
For instance, if you have a macro that uses play on a specific party member, allow this to be queued as a normal oGCD. 

E.g.: "/ac Play <5>"

At present, the only plugin that allows this is Redirect, but the release/updates appear to have slowed down.

**Comment by UnknownX7** [comment]
This is available through the use of `/macroqueue` or `/mqueue` which is designed to be used like `/merror` at the start of a macro. Although, I believe there is currently an issue where certain stacks can override it.

**Comment by geppeisenpai** [comment]
...okay, that's my bad. Thank you. I didn't realise it was a replacement for /merror. 

Thanks for the advice!
