### ISSUE TITLE
[Bug] Channeled Offensive Abilities Occasionally Instant Fail if Target is Moving with Enhanced Auto Face Target

### ISSUE THREAD

**Issue by vitharr137** [UnknownX7/ReAction#74]
Bug seems to be tough to replicate, but the issue appears most often with Flamethrower, Enhanced Auto Face Target, and a tank moving the target. Perhaps the simplest way to resolve it would be to add such offensive channels like Flamethrower, Phantom Flurry, etc to the blacklist from autofacing like heals are?

**Comment by UnknownX7** [comment]
Seems like an offset has changed, will be fixed in the next update.
