### ISSUE TITLE
[Issue] SMN summons and mouseover

### ISSUE THREAD

**Issue by lunyern123** [UnknownX7/ReAction#75]
This might not be an issue so much as how the skill itself works but thought it would be worth raising anyways.

When you set Summon Ifrit/Titan/Garuda to Field Target or UI Target, and use it on an enemy while they are deselected, the summon will appear but they will not execute their action (i.e. Inferno, Earthen Fury, Aerial Blast). Rather, they just stand there idly until they disappear a few seconds later without having done any damage.

When you have the target selected and then use the skill, however, they will execute their skills properly.

Could someone clarify if this is working as intended or an issue? 

How to replicate:
1. Set Summon Ifrit/Titan/Garuda to UI Target or Field Target.
2. Making sure the enemy/dummy is not selected as an active target, use the skill by mousing over the UI list or field target.
3. Watch the summons stand by idly after being summoned without executing their damaging skill.
4. Repeat step 2 with the target selected as an active target.

Can also confirm that adding their individual skills (i.e. Inferno, Earthen Fury, Aerial Blast) or Summon Carbuncle to the stack does not change the issue.

**Comment by UnknownX7** [comment]
Seems to be a game bug since it happens with a <mo> macro as well as if you queue the summon and then untarget the enemy. I assume the server is actually grabbing your target at the time of using the action to determine the target the summon should attack.
