### ISSUE TITLE
RPR Soul Scythe

### ISSUE THREAD

**Issue by FromTheGrayve** [UnknownX7/ReAction#77]
I cannot get the Reaper AoE action Soul Scythe #24381 to work in a stack.

**Comment by UnknownX7** [comment]
Soul scythe (and other AoEs centered on you) can only pass a stack if one of the targets resolves to yourself.

**Comment by FromTheGrayve** [comment]
Oh! Ill try it with Targets Target then?

**Comment by UnknownX7** [comment]
Can you give an example of how the stack is supposed to work? `Targets Target` would only work if you were tanking, `Self` is the only reliable way for it to pass.

**Comment by FromTheGrayve** [comment]
Self worked, thanks!
