### ISSUE TITLE
[Suggestion] add a secondary interval setting to turbo for very fast recast abilities (such as mudras and recuperate)

### ISSUE THREAD

**Issue by js43mk** [UnknownX7/ReAction#78]
turbo with very small interval is good on most abilities to make them feel more responsive. however, small intervals will cause very fast recast abilities to cast twice in a row, such as mudras

suggestion to add another interval setting for those skills, so that one can enjoy both a more responsive execution of normal abilities and no accidental double casting of these short recast abilities

**Comment by UnknownX7** [comment]
I will see what I can do, the feature is fairly hacky due to the way the game checks for keybinds so I have access to very little direct information about the actual hotbar slot.

**Comment by UnknownX7** [comment]
I've added a new lockout feature for queuing as well as an initial delay for turbo that should address this issue.
