### ISSUE TITLE
[Bug] After disabled "Queue Adjustments (BETA)", restart game the effect still there

### ISSUE THREAD

**Issue by Lornvene** [UnknownX7/ReAction#80]
1. Enable "Queue Adjustments (BETA)" and adjust queue threshold to 2.5, then disabled it.
2. Restart the game, it is still disabled.
3. Out of combat, everything normal. Start combat, queue threshold is 2.5

**Comment by UnknownX7** [comment]
Fixed by 1c379e79bdac820896548bcc872d7bb886a4d792 in the next release.
